name: Deploy Strapi App

on:
  push:
    branches-ignore: ["sprint"]

jobs:
  deploy:
    runs-on: [self-hosted, nodejs18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag registry.314ecorp.tech/practifly-cms:${{ github.ref_name }}

      - name: Push the Docker image
        run: docker push registry.314ecorp.tech/practifly-cms:${{ github.ref_name }}

      - name: Success Slack notification
        uses: slackapi/slack-github-action@v1.22.0
        if: job.status == 'success'
        with:
          channel-id: CMSM1CZ8Q
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: Build Success - ${{ github.repository }}/${{ github.ref_name }}"
                  },
                  "accessory": {
                    "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Logs",
                        "emoji": true
                      },
                      "value": "view_logs",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "action_id": "button-action"
                    }
                  }
                ]
              }
