name: cleanup-workflows
on:
  schedule:
    # Run every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  del_runs:
    runs-on:
      - self-hosted
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 5
